name: Daily Idea Generation

on:
  schedule:
    - cron: '10 0 * * *'  # 00:10 UTC every day
jobs:
  trigger-daily:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger generateDailyIdeas
        run: |
          curl -X GET https://${{ secrets.VERCEL_DOMAIN }}/api/generateDailyIdeas
