name: Hourly Pipelines

on:
  schedule:
    - cron: '0 * * * *'   # Every hour
jobs:
  trigger-hourly:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger scrapeTrending
        run: |
          curl -X GET https://${{ secrets.VERCEL_DOMAIN }}/api/scrapeTrending

      - name: Trigger computeSignals
        run: |
          curl -X GET https://${{ secrets.VERCEL_DOMAIN }}/api/computeSignals
